# Generated by Django 3.2.5 on 2021-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_companie', models.CharField(max_length=50)),
                ('website_companie', models.CharField(max_length=100)),
                ('tip_companie', models.CharField(max_length=50)),
            ],
        ),
    ]
